#!/bin/bash
# Merge text and image embedding databases into a unified database.
#
# The merged database can be used with the Detector class for kNN-based
# AI detection across both text and images.
#
# Prerequisites:
#   1. Text embedding database (from DeTree pipeline)
#   2. Image embedding database (from gen_image_emb.sh)
#
# Usage:
#   bash scripts/merge_db.sh

set -e

# ──────────────────────────────────────────────────────────────────────
# Configuration - adjust these paths as needed
# ──────────────────────────────────────────────────────────────────────

# Text database
TEXT_DATABASE="databases/text_compressed.pt"

# Image database (generated by gen_image_emb.sh)
IMAGE_DATABASE="databases/image_embeddings.pt"

# Target layer (all databases must share this layer key)
TARGET_LAYER=23

# Output path for the merged database
OUTPUT="databases/merged_multimodal.pt"

# ──────────────────────────────────────────────────────────────────────
# Run merge
# ──────────────────────────────────────────────────────────────────────

python -m detree.cli.merge_databases \
    --databases "$TEXT_DATABASE" "$IMAGE_DATABASE" \
    --target-layer "$TARGET_LAYER" \
    --output "$OUTPUT"

echo ""
echo "Merged database saved to: $OUTPUT"
