@echo off
REM Merge text and image embedding databases into a unified database (Windows version)

setlocal

REM ──────────────────────────────────────────────────────────────────────
REM Configuration - adjust these paths as needed
REM ──────────────────────────────────────────────────────────────────────

REM Text database
set TEXT_DATABASE=databases\text_compressed.pt

REM Image database (generated by gen_image_emb.bat)
set IMAGE_DATABASE=databases\image_embeddings.pt

REM Target layer (all databases must share this layer key)
set TARGET_LAYER=23

REM Output path for the merged database
set OUTPUT=databases\merged_multimodal.pt

REM ──────────────────────────────────────────────────────────────────────
REM Run merge
REM ──────────────────────────────────────────────────────────────────────

python -m detree.cli.merge_databases ^
    --databases "%TEXT_DATABASE%" "%IMAGE_DATABASE%" ^
    --target-layer %TARGET_LAYER% ^
    --output "%OUTPUT%"

echo.
echo Merged database saved to: %OUTPUT%

endlocal
