@echo off
REM Merge text and image embedding databases into a unified database (Windows version)

setlocal

REM ──────────────────────────────────────────────────────────────────────
REM Configuration - adjust these paths as needed
REM ──────────────────────────────────────────────────────────────────────

REM Text database
set TEXT_DATABASE=databases\priori1_center10k.pt

REM Image database (generated by gen_image_emb.bat)
set IMAGE_DATABASE=databases\image_embeddings_comp.pt

REM Output path for the merged database
set OUTPUT=databases\merged_multimodal_comp.pt

REM ──────────────────────────────────────────────────────────────────────
REM Run merge
REM ──────────────────────────────────────────────────────────────────────

python -m detree.cli.merge_databases ^
    --databases "%TEXT_DATABASE%" "%IMAGE_DATABASE%" ^
    --output "%OUTPUT%"

echo.
echo Merged database saved to: %OUTPUT%

endlocal
